import { Routes } from '@angular/router';
import { HomeComponent } from './components/home/home.component';
import { ToolDetailComponent } from './components/tools/tool-detail/tool-detail.component';
import { AppDetailComponent } from './components/apps/app-detail/app-detail.component';
import { ToolsComponent } from './components/tools/tools.component';
import { AppsComponent } from './components/apps/apps.component';
import { SponsorComponent } from './components/sponsor/sponsor.component';
import { JsonFormatterComponent } from './components/tools/01-json-formatter/json-formatter.component';
import { Base64EncoderComponent } from './components/tools/02-base64-encoder/base64-encoder.component';
import { QrCodeGeneratorComponent } from './components/tools/03-qr-code-generator/qr-code-generator.component';
import { ColorPickerComponent } from './components/tools/04-color-picker/color-picker.component';
import { TimestampConverterComponent } from './components/tools/05-timestamp-converter/timestamp-converter.component';
import { Md5HashComponent } from './components/tools/06-md5-hash/md5-hash.component';
import { UrlEncoderComponent } from './components/tools/07-url-encoder/url-encoder.component';
import { MortgageCalculatorComponent } from './components/tools/08-mortgage-calculator/mortgage-calculator.component';
import { JwtParserComponent } from './components/tools/09-jwt-parser/jwt-parser.component';
import { WebspherePasswordComponent } from './components/tools/10-websphere-password/websphere-password.component';
import { NumberConverterComponent } from './components/tools/11-number-converter/number-converter.component';
import { HashConverterComponent } from './components/tools/12-hash-converter/hash-converter.component';
import { CryptoEncryptorComponent } from './components/tools/13-crypto-encryptor/crypto-encryptor.component';
import { RegexTesterComponent } from './components/tools/14-regex-tester/regex-tester.component';
import { XmlFormatterComponent } from './components/tools/15-xml-formatter/xml-formatter.component';
import { CrontabCalculatorComponent } from './components/tools/16-crontab-calculator/crontab-calculator.component';
import { YamlJsonConverterComponent } from './components/tools/17-yaml-json-converter/yaml-json-converter.component';
import { SeveranceCalculatorComponent } from './components/tools/18-severance-calculator/severance-calculator.component';
import { SqlToErDiagramComponent } from './components/tools/19-sql-to-er-diagram/sql-to-er-diagram.component';
import { KeyboardTesterComponent } from './components/tools/20-keyboard-tester/keyboard-tester.component';
import { BambooGtdComponent } from './components/apps/01-bamboo-gtd/bamboo-gtd.component';
import { ArchitectureDesignComponent } from './components/apps/02-architecture-design/architecture-design.component';
import { ChronosComponent } from './components/apps/03-chronos/chronos.component';
import { VideoTranslatorComponent } from './components/apps/04-video-translator/video-translator.component';
import { UpWordComponent } from './components/apps/05-upword/upword.component';
import { YijunComponent } from './components/apps/06-yijun/yijun.component';
import { GitLoomComponent } from './components/apps/07-git-loom/git-loom.component';
import { MnemoraComponent } from './components/apps/08-mnemora/mnemora.component';
import { AiShortDramaComponent } from './components/apps/09-ai-short-drama/ai-short-drama.component';
import { PresentationGeneratorComponent } from './components/apps/10-presentation-generator/presentation-generator.component';
import { ComputerUseAgentComponent } from './components/apps/11-computer-use-agent/computer-use-agent.component';
import { DevilBrainComponent } from './components/apps/12-devil-brain/devil-brain.component';
import { FortuneLotteryComponent } from './components/apps/13-fortune-lottery/fortune-lottery.component';
import { SmartPasteComponent } from './components/apps/14-smart-paste/smart-paste.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'tools', component: ToolsComponent },
  { path: 'tools/json-formatter', component: JsonFormatterComponent },
  { path: 'tools/base64-encoder', component: Base64EncoderComponent },
  { path: 'tools/qr-code-generator', component: QrCodeGeneratorComponent },
  { path: 'tools/color-picker', component: ColorPickerComponent },
  { path: 'tools/timestamp-converter', component: TimestampConverterComponent },
  { path: 'tools/md5-hash', component: Md5HashComponent },
  { path: 'tools/url-encoder', component: UrlEncoderComponent },
  { path: 'tools/mortgage-calculator', component: MortgageCalculatorComponent },
  { path: 'tools/jwt-parser', component: JwtParserComponent },
  { path: 'tools/websphere-password', component: WebspherePasswordComponent },
  { path: 'tools/number-converter', component: NumberConverterComponent },
  { path: 'tools/hash-converter', component: HashConverterComponent },
  { path: 'tools/crypto-encryptor', component: CryptoEncryptorComponent },
  { path: 'tools/regex-tester', component: RegexTesterComponent },
  { path: 'tools/xml-formatter', component: XmlFormatterComponent },
  { path: 'tools/crontab-calculator', component: CrontabCalculatorComponent },
  { path: 'tools/yaml-json-converter', component: YamlJsonConverterComponent },
  { path: 'tools/severance-calculator', component: SeveranceCalculatorComponent },
  { path: 'tools/sql-to-er-diagram', component: SqlToErDiagramComponent },
  { path: 'tools/keyboard-tester', component: KeyboardTesterComponent },
  { path: 'tools/:id', component: ToolDetailComponent },
  { path: 'apps', component: AppsComponent },
  { path: 'apps/bamboo-gtd', component: BambooGtdComponent },
  { path: 'apps/architecture-design', component: ArchitectureDesignComponent },
  { path: 'apps/chronos', component: ChronosComponent },
  { path: 'apps/video-translator', component: VideoTranslatorComponent },
  { path: 'apps/upword', component: UpWordComponent },
  { path: 'apps/yijun', component: YijunComponent },
  { path: 'apps/git-loom', component: GitLoomComponent },
  { path: 'apps/mnemora', component: MnemoraComponent },
  { path: 'apps/ai-short-drama', component: AiShortDramaComponent },
  { path: 'apps/presentation-generator', component: PresentationGeneratorComponent },
  { path: 'apps/computer-use-agent', component: ComputerUseAgentComponent },
  { path: 'apps/devil-brain', component: DevilBrainComponent },
  { path: 'apps/fortune-lottery', component: FortuneLotteryComponent },
  { path: 'apps/smart-paste', component: SmartPasteComponent },
  { path: 'apps/:id', component: AppDetailComponent },
  { path: 'sponsor', component: SponsorComponent },
  { path: '**', redirectTo: '' }
];
