import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';

export type Language = 'zh' | 'en';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private currentLanguage$ = new BehaviorSubject<Language>('zh');
  
  translations: { [key: string]: { zh: string; en: string } } = {
    'site.name': { zh: '否兔联盟', en: '4oftools' },
    'nav.home': { zh: '首页', en: 'Home' },
    'nav.tools': { zh: '工具集', en: 'Tools' },
    'nav.apps': { zh: '应用', en: 'Apps' },
    'nav.ai': { zh: 'AI', en: 'AI' },
    'home.banner.title': { zh: '否兔联盟', en: '4oftools' },
    'home.banner.subtitle': { zh: '4oftools - 您的工具和应用集合平台', en: '4oftools - Your Tools and Apps Collection Platform' },
    'home.banner.description': { zh: '汇集了各种实用的在线工具和应用程序，让您的工作和生活更加便捷高效。', en: 'A collection of practical online tools and applications to make your work and life more convenient and efficient.' },
    'home.banner.explore': { zh: '探索工具', en: 'Explore Tools' },
    'home.banner.view': { zh: '查看应用', en: 'View Apps' },
    'home.tools.title': { zh: '工具集', en: 'Tools' },
    'home.tools.description': { zh: '精选的实用工具，帮助您提高工作效率', en: 'Curated practical tools to help improve your work efficiency' },
    'home.apps.title': { zh: '应用', en: 'Apps' },
    'home.apps.description': { zh: '功能丰富的应用程序，满足您的各种需求', en: 'Feature-rich applications to meet your various needs' },
    'home.view.more': { zh: '查看更多', en: 'View More' },
    'home.collapse': { zh: '收起', en: 'Collapse' },
    'tools.title': { zh: '工具集', en: 'Tools' },
    'tools.description': { zh: '精选的实用工具，帮助您提高工作效率', en: 'Curated practical tools to help improve your work efficiency' },
    'tools.count': { zh: '工具数量', en: 'Tools' },
    'apps.title': { zh: '应用', en: 'Apps' },
    'apps.description': { zh: '功能丰富的应用程序，满足您的各种需求', en: 'Feature-rich applications to meet your various needs' },
    'apps.count': { zh: '应用数量', en: 'Apps' },
    'filter.all': { zh: '全部', en: 'All' },
    'filter.programmer': { zh: '程序员', en: 'Programmer' },
    'filter.efficiency': { zh: '效率', en: 'Efficiency' },
    'filter.life': { zh: '生活', en: 'Life' },
    'filter.design': { zh: '设计', en: 'Design' },
    'filter.other': { zh: '其他', en: 'Other' },
    'tool.detail': { zh: '查看详情', en: 'View Details' },
    'tool.back': { zh: '返回首页', en: 'Back to Home' },
    'tool.use': { zh: '立即使用', en: 'Use Now' },
    'tool.link': { zh: '访问链接', en: 'Access Link' },
    'tool.intro': { zh: '详细介绍', en: 'Detailed Introduction' },
    'loading': { zh: '加载中...', en: 'Loading...' },
    'tool.notfound': { zh: '未找到该工具', en: 'Tool not found' },
    'footer.about': { zh: '关于我们', en: 'About Us' },
    'footer.about.text': { zh: '否兔联盟（4oftools）是一个集合了各种实用工具和应用的综合平台。我们致力于为用户提供便捷、高效的在线工具和应用程序。', en: '4oftools is a comprehensive platform that collects various practical tools and applications. We are committed to providing users with convenient and efficient online tools and applications.' },
    'footer.links': { zh: '快速链接', en: 'Quick Links' },
    'footer.contact': { zh: '联系方式', en: 'Contact' },
    'footer.email': { zh: '邮箱联系', en: 'Email' },
    'footer.feedback': { zh: '意见反馈', en: 'Feedback' },
    'ai.title': { zh: 'AI 前沿探索', en: 'AI Exploration' },
    'ai.subtitle': { zh: '探索最新的人工智能应用、产品和技术', en: 'Explore the latest AI applications, products and technologies' },
    'ai.description': { zh: '汇集了当前最热门和最有影响力的AI应用、产品和技术，帮助您了解人工智能领域的最新发展。', en: 'A collection of the hottest and most influential AI applications, products and technologies to help you understand the latest developments in artificial intelligence.' },
    'ai.filter.all': { zh: '全部', en: 'All' },
    'ai.filter.programming': { zh: 'AI编程工具', en: 'AI Programming Tools' },
    'ai.filter.model': { zh: 'AI底层模型', en: 'AI Foundation Models' },
    'ai.filter.image': { zh: 'AI图片技术', en: 'AI Image Technology' },
    'ai.filter.video': { zh: 'AI视频技术', en: 'AI Video Technology' },
    'ai.filter.other': { zh: '其他AI应用', en: 'Other AI Applications' },
    'ai.count': { zh: 'AI项目数量', en: 'AI Items' },
    'ai.visit': { zh: '访问网站', en: 'Visit Website' },
    'ai.learn': { zh: '了解更多', en: 'Learn More' },
    'empty.state': { zh: '暂无该分类的工具', en: 'No tools in this category' },
    'empty.apps': { zh: '暂无该分类的应用', en: 'No apps in this category' },
    'search.placeholder': { zh: '搜索工具...', en: 'Search tools...' },
    'search.placeholder.apps': { zh: '搜索应用...', en: 'Search apps...' },
    'search.placeholder.ai': { zh: '搜索AI项目...', en: 'Search AI items...' },
    'nav.sponsor': { zh: '赞助', en: 'Sponsor' },
    'sponsor.title': { zh: '赞助我们', en: 'Sponsor Us' },
    'sponsor.subtitle': { zh: '您的支持是我们持续发展的动力', en: 'Your support is the driving force for our continuous development' },
    'sponsor.wechat': { zh: '微信支付', en: 'WeChat Pay' },
    'sponsor.wechat.desc': { zh: '使用微信扫描二维码进行赞助', en: 'Scan the QR code with WeChat to sponsor' },
    'sponsor.alipay': { zh: '支付宝', en: 'Alipay' },
    'sponsor.alipay.desc': { zh: '使用支付宝扫描二维码进行赞助', en: 'Scan the QR code with Alipay to sponsor' },
    'sponsor.paypal': { zh: 'PayPal', en: 'PayPal' },
    'sponsor.paypal.desc': { zh: '点击图片或者扫描二维码通过 PayPal 进行赞助', en: 'Click the image or scan the QR code to sponsor via PayPal' },
    'sponsor.paypal.button': { zh: 'PayPal 赞助', en: 'Donate with PayPal' },
    'sponsor.qr.placeholder': { zh: '二维码图片', en: 'QR Code Image' },
    'sponsor.description.title': { zh: '关于赞助', en: 'About Sponsorship' },
    'sponsor.description.text1': { zh: '否兔联盟是一个免费的工具和应用集合平台，我们致力于为用户提供高质量的服务。', en: '4oftools is a free platform for tools and applications, and we are committed to providing users with high-quality services.' },
    'sponsor.description.text2': { zh: '您的赞助将帮助我们持续维护和开发新功能，改善用户体验，并支持服务器的运营成本。', en: 'Your sponsorship will help us continue to maintain and develop new features, improve user experience, and support server operating costs.' },
    'sponsor.description.text3': { zh: '我们非常感谢每一位支持者的慷慨捐助，您的名字将被记录在赞助商列表中。', en: 'We are very grateful for the generous donations from every supporter, and your name will be recorded in the sponsor list.' },
    'sponsor.sponsors.title': { zh: '赞助商列表', en: 'Sponsor List' },
    'sponsor.sponsors.corporate': { zh: '企业赞助商', en: 'Corporate Sponsors' },
    'sponsor.sponsors.individual': { zh: '个人赞助商', en: 'Individual Sponsors' },
    'sponsor.sponsors.empty': { zh: '暂无赞助商，成为第一个支持者吧！', en: 'No sponsors yet, be the first supporter!' },
    'sponsor.amount': { zh: '赞助金额', en: 'Amount' },
    'sponsor.date': { zh: '赞助日期', en: 'Date' },
    'footer.github': { zh: 'GitHub', en: 'GitHub' },
    'footer.copyright': { zh: '版权所有', en: 'All rights reserved' },
    'lang.zh': { zh: '中文', en: '中文' },
    'lang.en': { zh: 'EN', en: 'EN' },
    'logo.alt': { zh: '否兔联盟', en: '4oftools' },
    'qr.wechat.alt': { zh: '微信支付二维码', en: 'WeChat Pay QR Code' },
    'qr.alipay.alt': { zh: '支付宝二维码', en: 'Alipay QR Code' },
    'qr.paypal.alt': { zh: 'PayPal 赞助', en: 'PayPal Donate' },
    'app.notfound': { zh: '未找到该应用', en: 'App not found' },
    'tool.back.to.list': { zh: '返回列表', en: 'Back to List' },
    'json.formatter.title': { zh: 'JSON格式化工具', en: 'JSON Formatter' },
    'json.formatter.description': { zh: '快速格式化、验证和美化JSON数据，支持压缩和展开模式', en: 'Quickly format, validate and beautify JSON data with support for compressed and expanded modes' },
    'json.formatter.input': { zh: '输入', en: 'Input' },
    'json.formatter.output': { zh: '输出', en: 'Output' },
    'json.formatter.output.placeholder': { zh: '格式化后的JSON将显示在这里', en: 'Formatted JSON will appear here' },
    'json.formatter.format': { zh: '格式化', en: 'Format' },
    'json.formatter.compress': { zh: '压缩', en: 'Compress' },
    'json.formatter.validate': { zh: '验证', en: 'Validate' },
    'json.formatter.clear': { zh: '清空', en: 'Clear' },
    'json.formatter.copy': { zh: '复制', en: 'Copy' },
    'json.formatter.indent': { zh: '缩进', en: 'Indent' },
    'base64.title': { zh: 'Base64编解码器', en: 'Base64 Encoder/Decoder' },
    'base64.description': { zh: '在线Base64编码和解码工具，支持文本、图片等多种格式的Base64转换，操作简单快捷。', en: 'Online Base64 encoding and decoding tool supporting text, images and various formats.' },
    'base64.encode': { zh: '编码', en: 'Encode' },
    'base64.decode': { zh: '解码', en: 'Decode' },
    'base64.input': { zh: '输入文本', en: 'Input Text' },
    'base64.output': { zh: 'Base64输出', en: 'Base64 Output' },
    'base64.base64.input': { zh: 'Base64输入', en: 'Base64 Input' },
    'base64.text.output': { zh: '输出文本', en: 'Output Text' },
    'base64.input.placeholder': { zh: '请输入要编码的文本...', en: 'Enter text to encode...' },
    'base64.output.placeholder': { zh: '编码后的Base64字符串将显示在这里', en: 'Encoded Base64 string will appear here' },
    'base64.base64.input.placeholder': { zh: '请输入要解码的Base64字符串...', en: 'Enter Base64 string to decode...' },
    'base64.text.output.placeholder': { zh: '解码后的文本将显示在这里', en: 'Decoded text will appear here' },
    'qr.size': { zh: '尺寸', en: 'Size' },
    'qr.generate': { zh: '生成二维码', en: 'Generate QR Code' },
    'qr.download': { zh: '下载', en: 'Download' },
    'qr.input': { zh: '输入', en: 'Input' },
    'qr.output': { zh: '输出', en: 'Output' },
    'qr.input.placeholder': { zh: '请输入文本、URL或其他内容...', en: 'Enter text, URL or other content...' },
    'qr.placeholder.text': { zh: '生成的二维码将显示在这里', en: 'Generated QR code will appear here' },
    'qr.code.alt': { zh: '二维码', en: 'QR Code' },
    'color.format': { zh: '格式', en: 'Format' },
    'color.picker': { zh: '颜色选择器', en: 'Color Picker' },
    'color.info': { zh: '颜色信息', en: 'Color Information' },
    'color.current': { zh: '当前颜色', en: 'Current Color' },
    'color.hex': { zh: 'HEX', en: 'HEX' },
    'color.rgb': { zh: 'RGB', en: 'RGB' },
    'color.hsl': { zh: 'HSL', en: 'HSL' },
    'timestamp.to.date': { zh: '时间戳转日期', en: 'Timestamp to Date' },
    'date.to.timestamp': { zh: '日期转时间戳', en: 'Date to Timestamp' },
    'timestamp.convert': { zh: '转换', en: 'Convert' },
    'timestamp.current': { zh: '当前时间', en: 'Current Time' },
    'timestamp.input': { zh: '时间戳输入', en: 'Timestamp Input' },
    'timestamp.output': { zh: '时间戳输出', en: 'Timestamp Output' },
    'date.input': { zh: '日期输入', en: 'Date Input' },
    'date.output': { zh: '日期输出', en: 'Date Output' },
    'timestamp.input.placeholder': { zh: '请输入Unix时间戳（秒）...', en: 'Enter Unix timestamp (seconds)...' },
    'timestamp.output.placeholder': { zh: '转换后的时间戳将显示在这里', en: 'Converted timestamp will appear here' },
    'date.input.placeholder': { zh: '请输入日期时间...', en: 'Enter date and time...' },
    'date.output.placeholder': { zh: '转换后的日期将显示在这里', en: 'Converted date will appear here' },
    'md5.generate': { zh: '生成MD5', en: 'Generate MD5' },
    'md5.input': { zh: '输入', en: 'Input' },
    'md5.output': { zh: '输出', en: 'Output' },
    'md5.input.placeholder': { zh: '请输入要生成MD5哈希的文本...', en: 'Enter text to generate MD5 hash...' },
    'md5.output.placeholder': { zh: 'MD5哈希值将显示在这里', en: 'MD5 hash value will appear here' },
    'url.encode': { zh: '编码', en: 'Encode' },
    'url.decode': { zh: '解码', en: 'Decode' },
    'url.input': { zh: '输入', en: 'Input' },
    'url.output': { zh: 'URL编码输出', en: 'URL Encoded Output' },
    'url.encoded.input': { zh: 'URL编码输入', en: 'URL Encoded Input' },
    'url.decoded.output': { zh: '解码输出', en: 'Decoded Output' },
    'url.input.placeholder': { zh: '请输入要编码的文本或URL...', en: 'Enter text or URL to encode...' },
    'url.output.placeholder': { zh: '编码后的URL将显示在这里', en: 'Encoded URL will appear here' },
    'url.encoded.input.placeholder': { zh: '请输入要解码的URL编码字符串...', en: 'Enter URL-encoded string to decode...' },
    'url.decoded.output.placeholder': { zh: '解码后的文本将显示在这里', en: 'Decoded text will appear here' },
    'mortgage.loan.type': { zh: '贷款类型', en: 'Loan Type' },
    'mortgage.commercial.loan': { zh: '商业贷款', en: 'Commercial Loan' },
    'mortgage.provident.loan': { zh: '公积金贷款', en: 'Provident Fund Loan' },
    'mortgage.combined.loan': { zh: '组合贷款', en: 'Combined Loan' },
    'mortgage.loan.amount': { zh: '贷款总额', en: 'Loan Amount' },
    'mortgage.commercial.amount': { zh: '商业贷款金额', en: 'Commercial Loan Amount' },
    'mortgage.provident.amount': { zh: '公积金贷款金额', en: 'Provident Loan Amount' },
    'mortgage.loan.term': { zh: '贷款期限', en: 'Loan Term' },
    'mortgage.commercial.rate': { zh: '商业贷款利率', en: 'Commercial Rate' },
    'mortgage.provident.rate': { zh: '公积金贷款利率', en: 'Provident Rate' },
    'mortgage.payment.type': { zh: '还款方式', en: 'Payment Type' },
    'mortgage.equal.payment': { zh: '等额本息', en: 'Equal Payment' },
    'mortgage.equal.principal': { zh: '等额本金', en: 'Equal Principal' },
    'mortgage.monthly.payment': { zh: '月供', en: 'Monthly Payment' },
    'mortgage.total.interest': { zh: '总利息', en: 'Total Interest' },
    'mortgage.total.payment': { zh: '总还款额', en: 'Total Payment' },
    'mortgage.payment.details': { zh: '还款明细', en: 'Payment Details' },
    'mortgage.total.months': { zh: '总期数', en: 'Total Months' },
    'mortgage.month': { zh: '期数', en: 'Month' },
    'mortgage.principal': { zh: '本金', en: 'Principal' },
    'mortgage.interest': { zh: '利息', en: 'Interest' },
    'mortgage.monthly.total': { zh: '月供', en: 'Monthly Total' },
    'mortgage.remaining': { zh: '剩余本金', en: 'Remaining' },
    'mortgage.yuan': { zh: '元', en: 'Yuan' },
    'mortgage.years': { zh: '年', en: 'Years' },
    'mortgage.months': { zh: '期', en: 'Months' },
    'mortgage.showing.first': { zh: '显示前', en: 'Showing first' },
    'mortgage.total': { zh: '共', en: 'Total' },
    'jwt.input.token': { zh: 'JWT Token', en: 'JWT Token' },
    'jwt.input.placeholder': { zh: '请输入JWT token...', en: 'Enter JWT token...' },
    'jwt.header': { zh: 'Header', en: 'Header' },
    'jwt.payload': { zh: 'Payload', en: 'Payload' },
    'jwt.signature': { zh: 'Signature', en: 'Signature' },
    'jwt.expiration': { zh: '过期时间', en: 'Expiration' },
    'jwt.issued.at': { zh: '签发时间', en: 'Issued At' },
    'jwt.issuer': { zh: '签发者', en: 'Issuer' },
    'jwt.subject': { zh: '主题', en: 'Subject' },
    'jwt.expired': { zh: '已过期', en: 'Expired' },
    'jwt.valid': { zh: '有效', en: 'Valid' },
    'jwt.time.until.expiration': { zh: '剩余时间', en: 'Time Until Expiration' },
    'websphere.encrypt': { zh: '加密', en: 'Encrypt' },
    'websphere.decrypt': { zh: '解密', en: 'Decrypt' },
    'websphere.input.text': { zh: '输入文本', en: 'Input Text' },
    'websphere.input.encrypted': { zh: '输入加密内容', en: 'Input Encrypted Text' },
    'websphere.output.encrypted': { zh: '加密输出', en: 'Encrypted Output' },
    'websphere.output.text': { zh: '解密输出', en: 'Decrypted Output' },
    'websphere.input.placeholder': { zh: '请输入要加密的文本...', en: 'Enter text to encrypt...' },
    'websphere.encrypted.placeholder': { zh: '请输入要解密的加密内容（以{xor}开头）...', en: 'Enter encrypted text to decrypt (starting with {xor})...' },
    'websphere.output.placeholder': { zh: '加密后的内容将显示在这里（以{xor}开头）', en: 'Encrypted content will appear here (starting with {xor})' },
    'websphere.decrypted.placeholder': { zh: '解密后的文本将显示在这里', en: 'Decrypted text will appear here' },
    'websphere.info.title': { zh: '关于WebSphere密码加密', en: 'About WebSphere Password Encryption' },
    'websphere.info.description': { zh: 'WebSphere Application Server使用XOR加密算法来加密密码。加密后的密码以{xor}前缀开头。', en: 'WebSphere Application Server uses XOR encryption algorithm to encrypt passwords. Encrypted passwords start with {xor} prefix.' },
    'websphere.info.point1': { zh: '加密算法：XOR加密，使用"WebSphere"作为密钥', en: 'Encryption Algorithm: XOR encryption using "WebSphere" as the key' },
    'websphere.info.point2': { zh: '加密格式：{xor} + Base64编码的XOR加密结果', en: 'Encryption Format: {xor} + Base64 encoded XOR encryption result' },
    'websphere.info.point3': { zh: '用途：主要用于WebSphere配置文件中的密码加密存储', en: 'Usage: Mainly used for encrypted password storage in WebSphere configuration files' },
    'xml.formatter.format': { zh: '格式化', en: 'Format' },
    'xml.formatter.compress': { zh: '压缩', en: 'Compress' },
    'xml.formatter.validate': { zh: '验证', en: 'Validate' },
    'xml.formatter.indent': { zh: '缩进', en: 'Indent' },
    'xml.formatter.input': { zh: '输入', en: 'Input' },
    'xml.formatter.output': { zh: '输出', en: 'Output' },
    'xml.formatter.output.placeholder': { zh: '格式化后的XML将显示在这里', en: 'Formatted XML will appear here' },
    'number.from': { zh: '从', en: 'From' },
    'number.to': { zh: '到', en: 'To' },
    'number.convert': { zh: '转换', en: 'Convert' },
    'number.binary': { zh: '二进制', en: 'Binary' },
    'number.octal': { zh: '八进制', en: 'Octal' },
    'number.decimal': { zh: '十进制', en: 'Decimal' },
    'number.hexadecimal': { zh: '十六进制', en: 'Hexadecimal' },
    'number.input': { zh: '输入', en: 'Input' },
    'number.output': { zh: '输出', en: 'Output' },
    'number.input.placeholder': { zh: '请输入数字...', en: 'Enter number...' },
    'number.output.placeholder': { zh: '转换结果将显示在这里', en: 'Converted result will appear here' },
    'hash.algorithm': { zh: '算法', en: 'Algorithm' },
    'hash.input': { zh: '输入', en: 'Input' },
    'hash.output': { zh: '哈希值', en: 'Hash' },
    'hash.input.placeholder': { zh: '请输入要生成哈希的文本...', en: 'Enter text to generate hash...' },
    'hash.output.placeholder': { zh: '生成的哈希值将显示在这里', en: 'Generated hash will appear here' },
    'crypto.algorithm': { zh: '算法', en: 'Algorithm' },
    'crypto.password': { zh: '密码', en: 'Password' },
    'crypto.password.placeholder': { zh: '请输入密码...', en: 'Enter password...' },
    'crypto.encrypt': { zh: '加密', en: 'Encrypt' },
    'crypto.decrypt': { zh: '解密', en: 'Decrypt' },
    'crypto.input.text': { zh: '输入文本', en: 'Input Text' },
    'crypto.input.encrypted': { zh: '输入加密内容', en: 'Input Encrypted Text' },
    'crypto.output.encrypted': { zh: '加密输出', en: 'Encrypted Output' },
    'crypto.output.text': { zh: '解密输出', en: 'Decrypted Output' },
    'crypto.input.placeholder': { zh: '请输入要加密的文本...', en: 'Enter text to encrypt...' },
    'crypto.encrypted.placeholder': { zh: '请输入要解密的加密内容...', en: 'Enter encrypted text to decrypt...' },
    'crypto.output.placeholder': { zh: '加密后的内容将显示在这里', en: 'Encrypted content will appear here' },
    'crypto.decrypted.placeholder': { zh: '解密后的文本将显示在这里', en: 'Decrypted text will appear here' },
    'regex.pattern': { zh: '正则表达式', en: 'Regex Pattern' },
    'regex.pattern.placeholder': { zh: '例如: /\\d+/', en: 'e.g., /\\d+/' },
    'regex.flags': { zh: '标志', en: 'Flags' },
    'regex.flags.placeholder': { zh: 'gim', en: 'gim' },
    'regex.test': { zh: '测试', en: 'Test' },
    'regex.test.text': { zh: '测试文本', en: 'Test Text' },
    'regex.test.placeholder': { zh: '请输入要测试的文本...', en: 'Enter text to test...' },
    'regex.results': { zh: '匹配结果', en: 'Match Results' },
    'regex.no.matches': { zh: '没有匹配项', en: 'No matches found' },
    'crontab.expression': { zh: 'Cron表达式', en: 'Cron Expression' },
    'crontab.placeholder': { zh: '例如: 0 0 * * *', en: 'e.g., 0 0 * * *' },
    'crontab.calculate': { zh: '计算', en: 'Calculate' },
    'crontab.description': { zh: '描述', en: 'Description' },
    'crontab.next.runs': { zh: '下次执行时间', en: 'Next Run Times' },
    'crontab.minute': { zh: '分钟', en: 'Minute' },
    'crontab.hour': { zh: '小时', en: 'Hour' },
    'crontab.day': { zh: '日期', en: 'Day' },
    'crontab.month': { zh: '月份', en: 'Month' },
    'crontab.weekday': { zh: '星期', en: 'Weekday' },
    'crontab.info.title': { zh: 'Cron表达式格式', en: 'Cron Expression Format' },
    'crontab.info.description': { zh: 'Cron表达式由5个字段组成，用空格分隔：', en: 'Cron expression consists of 5 fields separated by spaces:' },
    'yaml.yaml.to.json': { zh: 'YAML转JSON', en: 'YAML to JSON' },
    'yaml.json.to.yaml': { zh: 'JSON转YAML', en: 'JSON to YAML' },
    'yaml.convert': { zh: '转换', en: 'Convert' },
    'yaml.yaml.input': { zh: 'YAML输入', en: 'YAML Input' },
    'yaml.json.input': { zh: 'JSON输入', en: 'JSON Input' },
    'yaml.yaml.output': { zh: 'YAML输出', en: 'YAML Output' },
    'yaml.json.output': { zh: 'JSON输出', en: 'JSON Output' },
    'yaml.yaml.placeholder': { zh: '请输入YAML内容...', en: 'Enter YAML content...' },
    'yaml.json.placeholder': { zh: '请输入JSON内容...', en: 'Enter JSON content...' },
    'yaml.yaml.output.placeholder': { zh: '转换后的YAML将显示在这里', en: 'Converted YAML will appear here' },
    'yaml.json.output.placeholder': { zh: '转换后的JSON将显示在这里', en: 'Converted JSON will appear here' }
  };

  constructor() {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && (savedLang === 'zh' || savedLang === 'en')) {
      this.currentLanguage$.next(savedLang);
    }
  }

  getCurrentLanguage(): Observable<Language> {
    return this.currentLanguage$.asObservable();
  }

  setLanguage(lang: Language) {
    this.currentLanguage$.next(lang);
    localStorage.setItem('language', lang);
  }

  translate(key: string): string {
    const lang = this.currentLanguage$.value;
    return this.translations[key]?.[lang] || key;
  }

  get currentLang(): Language {
    return this.currentLanguage$.value;
  }
}

